### PR TITLE
fix for aws-provider 3.0

### LINKED ISSUE #26: Update to aws-provider version 3.0
## Describe the Bug
See: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-3-upgrade#domain_validation_options-changed-from-list-to-set

## Expected Behavior
Module should not error out when upgrading provider to 3.0.

## Steps to Reproduce
1. Pin aws-provider to 3.0
2. Run 'terraform apply' on an existing module
4. See error similar to error documented on the upgrade notes

### PR DESCRIPTION
**Pull request by geota**
## what
* handles breaking change for terraform provider 3.0 https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-3-upgrade#domain_validation_options-changed-from-list-to-set

## why
* support aws provider 3.0

## notes
This does not recreate the cert, but will recreate the DNS validation records. This is ok, because the route53 record resource already had allow_overwrite set to true. No outputs or variables were changed. 

## references
closes #26

### CODE REVIEW

**Comment by Gowiem** [comment]
@geota This seems to break tests and doesn't seem to update the aws provider pinning. Have you used this on a project successfully? Any thoughts on the broken tests or not changing the aws provider pin?

**Comment by geota** [comment]
@Gowiem  yes, we are using this in production and is working fine. It did not destroy our existing certs but did require manually working through the linked terraform 3 upgrade notes for this.

**Comment by geota** [comment]
```
TestExamplesComplete 2020-08-12T01:45:19Z command.go:121: Error: Invalid for_each argument
TestExamplesComplete 2020-08-12T01:45:19Z command.go:121: 
TestExamplesComplete 2020-08-12T01:45:19Z command.go:121:   on ../../main.tf line 26, in resource "aws_route53_record" "default":
TestExamplesComplete 2020-08-12T01:45:19Z command.go:121:   26:   for_each = {
TestExamplesComplete 2020-08-12T01:45:19Z command.go:121:   27:     for dvo in local.domain_validation_options_list : dvo.domain_name => {
TestExamplesComplete 2020-08-12T01:45:19Z command.go:121:   28:       name   = dvo.resource_record_name
TestExamplesComplete 2020-08-12T01:45:19Z command.go:121:   29:       record = dvo.resource_record_value
TestExamplesComplete 2020-08-12T01:45:19Z command.go:121:   30:       type   = dvo.resource_record_type
TestExamplesComplete 2020-08-12T01:45:19Z command.go:121:   31:     }
TestExamplesComplete 2020-08-12T01:45:19Z command.go:121:   32:   }
TestExamplesComplete 2020-08-12T01:45:19Z command.go:121: 
TestExamplesComplete 2020-08-12T01:45:19Z command.go:121: The "for_each" value depends on resource attributes that cannot be determined
TestExamplesComplete 2020-08-12T01:45:19Z command.go:121: until apply, so Terraform cannot predict how many instances will be created.
TestExamplesComplete 2020-08-12T01:45:19Z command.go:121: To work around this, use the -target argument to first apply only the
TestExamplesComplete 2020-08-12T01:45:19Z command.go:121: resources that the for_each depends on.
```

I tested this successfully on Terraform 0.13 and AWS Provider 3.0 on an existing already applied module.

My guess is the above issue is related to the `for_each` depending on `local.domain_validation_options_list` which in the module depends on `aws_acm_certificate.default.0.domain_validation_option` and on a clean apply fails because of the dependency and terraform not able to resolve it until runtime. 

```
  domain_validation_options_list    = local.process_domain_validation_options ? aws_acm_certificate.default.0.domain_validation_options : []
```

The real fix is probably reverting this and translating the terraform aws-provider 3.0 upgrade notes into the count structure that this module was using. TBH, I do not have time to pick this up and was mainly just fixing a production issue that we hit when upgrading to 3.0. Feel free to close this out.

**Comment by osterman** [comment]
@geota [`master` is pinned to `~> 2.0`](https://github.com/cloudposse/terraform-aws-acm-request-certificate/blob/master/versions.tf#L5) of the `aws` provider. Like @Gowiem says, this doesn't pin to 3.0, so it can't possibly be verified against the 3.0 provider.

**Comment by Gowiem** [comment]
@geota We just merged #29, which addresses the provider 2.x lock and passed tests. Can you revaluate this PR and describe why these changes are needed as I'm confused on that front.
